[package]
name = "femtoclaw-claws"
version = "1.0.3"
edition = "2021"
license = "Apache-2.0"
description = "FemtoClaw Capability Modules and Tool Integration Core Library"
repository = "https://github.com/femtoclaw/femtoclaw-claws.git"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["process", "rt-multi-thread", "macros", "fs"] }

[lib]
name = "femtoclaw_claws"
path = "src/lib.rs"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = "z"
